### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by Jayman2000** [MartinMouritzen/Podfriend#12]
When I run `yarn` on Windows, this is what happens:

```
C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend>yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @ionic-native/background-mode@5.32.1" has unmet peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning " > @ionic-native/core@5.32.0" has unmet peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning " > @ionic-native/media@5.32.0" has unmet peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning " > @ionic-native/music-controls@5.32.1" has unmet peer dependency "rxjs@^5.5.0 || ^6.5.0".
warning " > @ionic/react-router@5.5.3" has unmet peer dependency "@ionic/core@5.5.3".
warning " > react-dotdotdot@1.3.1" has unmet peer dependency "prop-types@*".
warning "react-qr-code > @react-native-community/art@1.2.0" has unmet peer dependency "react-native@*".
warning " > react-rewards@1.1.2" has unmet peer dependency "prop-types@^15.5.4".
warning "react-rewards > react-pose > popmotion-pose > pose-core > rollup-plugin-typescript2@0.25.3" has unmet peer dependency "rollup@>=1.26.3".
warning " > react-spring-bottom-sheet@3.2.1" has incorrect peer dependency "react@^16.14.0 || 17".
warning " > react-use-dimensions@1.2.1" has unmet peer dependency "@types/react@^16.8.20".
warning " > react-use-dimensions@1.2.1" has unmet peer dependency "typescript@^3.5.2".
warning " > system-control@0.1.1" has incorrect peer dependency "win-audio@^1.2.0".
warning " > system-control@0.1.1" has incorrect peer dependency "loudness@git+https://github.com/RyanAfrish7/node-loudness.git".
warning " > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
warning " > connected-react-router@5.0.1" has incorrect peer dependency "react-redux@^4.4.8 || ^5.0.7".
warning " > connected-react-router@5.0.1" has incorrect peer dependency "react-router@^4.3.1".
[4/4] Building fresh packages...
[-/13] ⠈ waiting...
[2/13] ⠈ node-sass
[13/13] ⠈ win-audio
[10/13] ⠈ electron
error C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Anon Y. Mous\\Documents\\Home\\VC\\Podfriend\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Anon Y. Mous\\Documents\\Home\\VC\\Podfriend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend\node_modules\node-sass
gyp ERR! node -v v16.4.0





C:\Users\Anon Y. Mous\Documents\Home\VC\Podfriend>
```

**Comment by MartinMouritzen** [comment]
Hi sorry for the late reply!

If I read your debug log correctly, it seems that python is missing. I will try to see if I can add that as a dependency so it install automatically.

Until then here's some directions for you, in case they are of value to you :)
https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp
